### ISSUE TITLE
Lack of dataset description/examples

### ISSUE THREAD

**Issue by crj1998** [j-min/VPGen#1]
When I try to reproduce result, I found that the README lacks a description of the content structure of the dataset and does not provide `flickr30k_coco_paintskills` dataset, therefore cannot be replicated. 
Can you provide a demo?

**Comment by crj1998** [comment]
Also, there need a `text2box.json` which not provided.
https://github.com/j-min/VPGen/blob/e8648214610e497833ddb61d6e4e234ccc291149/utils/prompter.py#L18

**Comment by hujunchao** [comment]
+1

**Comment by Show-han** [comment]
+1, have you solved this?

**Comment by j-min** [comment]
Hi all, thanks for your interest in our project, and sorry for the delay.

I just uploaded the training data file at [HF Hub](https://huggingface.co/j-min/VPGen/blob/main/flickr30k_coco_paintskills_text2box_train.json) and the [text2box.json](https://github.com/j-min/VPGen/blob/main/templates/text2box.json) and updated the README.
