### ISSUE TITLE
Checkpoint for LoRA

### ISSUE THREAD

**Issue by ZiAngGu1** [j-min/VPGen#2]
Hi there,
    Thanks for this great work, it is making an excellent contribution to the community.
    I want to try your inference stage. Could you provide the checkpoint for the LoRA?
    Thank you for your time!
Sincerely,
ZiAng

**Comment by j-min** [comment]
Hi @ZiAng1-G, thanks for your interest in our project!
I just updated our [Readme](https://github.com/j-min/VPGen#download-pre-processed-vicuna-13b--lora-checkpoints-from-hf-hub) with LoRA checkpoint and provide a [Colab Demo](https://colab.research.google.com/github/j-min/VPGen/blob/main/VPGen_Demo.ipynb).

**Comment by ZiAngGu1** [comment]
Thanks for the reply
