### ISSUE TITLE
Can you release the training data & training prompts?

### ISSUE THREAD

**Issue by Show-han** [j-min/VPGen#3]
I notices you miss some important file for training the vicuna lora, e.g., the data you use (what is the data format), and prompt template (text2box). Could you please release them and provide a download link? So I can train the lora on my machine. And I don't think that those files are too big, and it will be helpful for following works if you provide the detailed training data/files.

**Comment by j-min** [comment]
Hi @Show-han, thanks for your interest in our project!

I just added the template file [text2box.json](https://github.com/j-min/VPGen/blob/main/templates/text2box.json) to the github repo, and added training data to the [HF Hub](https://huggingface.co/j-min/VPGen/blob/main/flickr30k_coco_paintskills_text2box_train.json).
